### ISSUE TITLE
html conversion doesn't work for links/references

### ISSUE THREAD

**Issue by j-rausch** [spencermountain/dumpster-dive#58] opened 2018-09-06 06:15 UTC
Hey,
I noticed that the generated html documents seem to be missing a bunch of linked/referenced information.
For instance, here's some snippets of the dumpster-generated Wikipedia article for Abraham Lincoln and the original reference:

### Dumpster 1:
![dumpster1](https://user-images.githubusercontent.com/38429553/45138236-933c9d00-b160-11e8-8e4b-1defdd2e9625.png)

### Original 1:
![orig1](https://user-images.githubusercontent.com/38429553/45138241-9899e780-b160-11e8-959b-8939118a6aed.png)

### Dumpster 2:
![dumpster2](https://user-images.githubusercontent.com/38429553/45138249-a0f22280-b160-11e8-89d7-d4a9e3c807e1.png)

### Original 2:
![orig2](https://user-images.githubusercontent.com/38429553/45138260-a64f6d00-b160-11e8-9477-d6bd2a1e60b9.png)

In case it's convenient, here's the relevant json and the converted html (Both generated with `3.1.0`).

[Abraham_Lincoln_json.txt](https://github.com/spencermountain/dumpster-dive/files/2355721/Abraham_Lincoln_json.txt)

[Abraham_Lincoln_html.txt](https://github.com/spencermountain/dumpster-dive/files/2355722/Abraham_Lincoln_html.txt)
Cheers

**Comment by spencermountain** [comment] 2018-09-06 13:20
whoa, weird. that's the output that's stored in mongo, after running `--html=true`?
i haven't been able to reproduce this directly
https://runkit.com/spencermountain/5b912901c133fe0012ebfc8f
i will check it out in detail later on

**Comment by j-rausch** [comment] 2018-09-06 17:54
Yeah, that's the output for `--html=true`. You mentioned it works in your example (`5.2.1`), so ideally it is already fixed by now. Dumpster-dive `3.1.0` has the dependency `"wtf_wikipedia": "^3.1.1"`. I just checked, and that's also the one that's being installed, if you run `npm install -g` in the `3.1.0` dumpster-dive directory.

**Comment by aymansalama** [comment] 2018-09-21 12:29
@j-rausch @spencermountain  i am using dumpster 3.6.1 with the below command 
dumpster enwiki-latest-pages-articles.xml --html=true --images=false --batch_size 100 --verbose true --workers 20

i tried this 3 times till now and i can't get more than 1.2 M articles. How did you get 5M articles uploaded? 

am i doing something wrong? I am using enwiki of 1st of sept 2018 dump. I can find articles in xml dump and not in the mongo files

**Comment by spencermountain** [comment] 2018-09-21 17:02
hey @aymansalama yeah, rats. that sounds like trouble.
I don't think you're doing anything wrong.
what happens at the end? are there any error messages? Does the script finish?

I'm working on wtf-wikipedia v6, and will update this library with some more logging when that's ready. If not today, then monday.
cheers

**Comment by aymansalama** [comment] 2018-09-21 17:27
@spencermountain i am not sure that I understand all the parameter correctly. I referred to your file in bin folder but still kindly i need more info if possible "forgive me".  [https://github.com/spencermountain/dumpster-dive/blob/master/bin/dumpster.js](url)
I am running the script again with the below parameters 
 enwiki-latest-pages-articles.xml --citations=false --html=true --batch_size 100
I updated the version of dumpster to 3.6.1 using npm

i am combing the dumpster with sudo nohup dumpster enwiki..... to be able to run it in the background on the cloud. I have to use sudo or for some reason the process will be killed with the termination of the user.

**Comment by spencermountain** [comment] 2018-09-21 17:35
yeah, I don't know what's wrong. I recommend grabbing a small wiki, adding some logging, and poking around to see what's missing. I would presume there would be some error messages, if pages are being missed.

i've never used `nohup`, is it possible that's ignoring the kill-command to the workers?
using the bin file should work. Let me know if you can find out any details.

**Comment by aymansalama** [comment] 2018-09-21 17:39
@spencermountain 
_what happens at the end?_ 
the script finsiehd successfully 

_are there any error messages?_ 
the verbos mode makes it too messy. to much logs. it is almost 1G file of logs. which is difficult and time consuming to search for errors. I have run many trials and i was hoping for quick results. 
the error that i notices
**error 16mb:** when i don't configure the batch with 100 size, the error appear.
**error duplicate :**  -- 100  duplicate pages -- I am not sure if this an error or not. The title around this error are successfully uploaded.  
**error in unicode:** I have noticed some problems with unicode display. but this is too complciated for me to get the cause. it might be anythin. 



_Does the script finish?_
yes, it does

**Comment by aymansalama** [comment] 2018-09-21 17:41
@spencermountain 
 is it possible that's ignoring the kill-command to the workers? maybe, i will have to try again. 
i will keep diagnosing and I will let you know. enjoy your weekend.

**Comment by aymansalama** [comment] 2018-09-21 17:44
@spencermountain just quick question
if i use the option --images=false, will it ignore the whole page that contain image info?

**Comment by spencermountain** [comment] 2018-09-21 18:21
ah no, images=false should just skip that part of the json result.
i'd run verbose-true, and see which pages are getting skipped. 
i'd put a few console.logs [here](https://github.com/spencermountain/dumpster-dive/blob/master/src/worker/02-parseWiki.js#L22) to see what's not getting through.
thanks, good luck!

**Comment by aymansalama** [comment] 2018-09-21 18:33
@spencermountain thanks a million
i noticed that my current run is progressing and output is keep popping but the number of pages doesnt increase for like half an hour now. and only keep giving duplicate. so i choose on page title and grep in the output and here is the results. Please note the number at the beginning of each line which is the number of line in the output. It seems that the same page is processed by multiple core or something? what do you think?
sorry for spamming you with many questions. 
```

sudo grep -n 'American wigeon' nohup.out 
15517: #8  +100 pages  -  193ms - "American wigeon"
15519: #12  +0 pages  -  172ms - "American wigeon"
15538: #11  +0 pages  -  190ms - "American wigeon"
31954: #9  +0 pages  -  210ms - "American wigeon"
31958: #5  +0 pages  -  204ms - "American wigeon"
33109: #3  +0 pages  -  157ms - "American wigeon"
33121: #1  +0 pages  -  175ms - "American wigeon"
43075: #14  +0 pages  -  324ms - "American wigeon"
43077: #4  +0 pages  -  344ms - "American wigeon"
43093: #0  +0 pages  -  169ms - "American wigeon"
43247: #6  +0 pages  -  173ms - "American wigeon"
43253: #15  +0 pages  -  154ms - "American wigeon"
43257: #10  +0 pages  -  173ms - "American wigeon"
45677: #2  +0 pages  -  206ms - "American wigeon"
45693: #13  +0 pages  -  198ms - "American wigeon"
45719: #7  +0 pages  -  212ms - "American wigeon"
```

**Comment by spencermountain** [comment] 2018-09-21 18:37
yeah, looks like the workers are getting stuck.
I'll take a look, you may want to revert back to a previous version of dumpster-dive. I think `3.1.0` is our most successful....

**Comment by aymansalama** [comment] 2018-09-21 18:50
@spencermountain cool, I have downgraded the package to 3.1.0 and started a fresh test for enwiki. in the same time, I have another machine testing 3.6.0. lets see who will win 👍

**Comment by aymansalama** [comment] 2018-09-22 02:37
@spencermountain I have tried with 3.1.0 version and i got 186,441 pages only. 

1. i used only --batch_size 100 parameter
2. The script finished successfully 
3. no error were generated except "duplicate pages"
4. This page was stuck and the same output message kept alarming for 431 times "current: 186,441 pages  - "Argument (disambiguation)""

> Here is the last part of the script. 

      👍  closing down.

     -- final count is 186,441 pages --
       took 3.0 hours

> Here is the database count

> show dbs
admin   0.000GB
config  0.000GB
enwiki  2.735GB
local   0.000GB
> use enwiki
switched to db enwiki
> db.pages.count()
186441

**Comment by spencermountain** [comment] 2018-09-24 22:17
original html-output issue seems to be working now in v`4.0.0`, lemme know if it isn't.
will address the @aymansalama stuck workers in #65 
cheers

**Closed by spencermountain** 2018-09-24 22:17 UTC
Labels: bug
