### ISSUE TITLE
16mb record issue

### ISSUE THREAD

**Issue by j-rausch** [spencermountain/dumpster-dive#57] opened 2018-08-21 07:18 UTC
Thanks a lot for sharing and maintaining this amazing project!

I would like to parse all articles from the "enwiki-latest-pages-articles.xml" (02 Aug. 2018; with --html flag) and noticed that the parser seems to gets "stuck" on specific entries. Instead of skipping the article, parsing essentially comes to a halt. The script is still running, but does not proceed beyond the current entry:
```

...
     current: 3,877,976 pages - "Vapor–liquid separator"     


     current: 3,877,976 pages - "Vapor–liquid separator"     


     current: 3,877,976 pages - "Vapor–liquid separator"     


     current: 3,877,976 pages - "Vapor–liquid separator"     


     current: 3,877,976 pages - "Vapor–liquid separator"     
...
```

There are no errors being thrown. In a previous attempt to parse a full dump from 2017, the same behavior occurred (for a different article).

**Comment by spencermountain** [comment] 2018-08-21 14:40
whoa thanks, yeah that sounds like trouble.
something brought-down all the workers, and there was no error message?

yeah, my guess is that Vapor-liquid separator is fine, but it's something in the next batch causing the problem.

here, why don't I update this repo to the latest parser, and add a verbose-mode, so we can see what's going on.

**Comment by j-rausch** [comment] 2018-08-21 16:47
Thanks! No, there's no error message whatsoever. 
I could repeat parsing after the update and get back to you with the results of that run.

By the way, I was looking for a verbose option earlier. It is mentioned in the changelog for 2.4.0, but doesn't seem to be featured in the actual code anymore.

**Comment by dapick** [comment] 2018-08-24 20:15
Hey there ✋

I also have the same problem, just a different page make it stuck:
![image](https://user-images.githubusercontent.com/33779948/44605795-5208cc80-a7f3-11e8-9fac-140704704414.png)

Any progress understanding why this is happening?

**Comment by j-rausch** [comment] 2018-08-24 21:01
I didn't further look into it.

Did you install dumpster-dive locally from the master branch of this repo?
If yes, then you might be able to run it smoothly for now, by using version 3.1.0 instead:
While in the cloned repo, type:
`git checkout tags/3.1.0`
And then install locally.

**Comment by spencermountain** [comment] 2018-08-27 16:42
hey, thanks for the update. Have a few bugs fixed in the parser, and will update dumpster this afternoon, to see if that clears things up.

Either way, having it fail silently like that is bad-news.

my guess is that it's an issue with html/template parsing, introduced in the past few versions. Will check it out.

**Comment by spencermountain** [comment] 2018-08-27 16:44
if anyone wants to impliment a dirty logger, to see which article is killing the worker, you could add a quick `console.log(page.title)` [here](https://github.com/spencermountain/dumpster-dive/blob/master/src/worker/01-parsePage.js#L46)

**Comment by spencermountain** [comment] 2018-09-04 19:52
hey, i've fixed a bunch of bugs that have popped up in recent versions of the markup parser, and any one of these could have been killing the workers.  

please check out `3.5.0`, when you have time.

it runs smoothly for me, but if you have the same issue, you can now run
```js
dumpster({verbose:true})
```
to find the problematic articles. That makes a debug much easier.
cheers

**Comment by j-rausch** [comment] 2018-09-04 21:13
Hi, thank you for the updates! 
I just tried running the current master (the latest tag I could find was `3.1.0`) and there seems to be an issue with the wtf_wikpedia parser:
```
---Error on "Virginia International Raceway"
TypeError: i.json is not a function
    at data.images.doc.images.map.i (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/toJson.js:43:43)
    at Array.map (<anonymous>)
    at toJSON (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/toJson.js:43:32)
    at Document.json (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/Document.js:152:12)
    at parseWiki (/home/jrausch/.npm/lib/node_modules/dumpster-dive/src/worker/02-parseWiki.js:31:18)
    at SundayDriver.each (/home/jrausch/.npm/lib/node_modules/dumpster-dive/src/worker/index.js:29:16)
    at SundayDriver.doChunk (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/index.js:38:8)
    at doit (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/index.js:77:10)
    at SundayDriver.onData (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/index.js:87:3)
    at ReadStream.stream.on (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/02-start.js:15:10)
```

Cheers

**Comment by spencermountain** [comment] 2018-09-05 15:37
ah, rats. 
thanks, I will look at it this weekend.
looks like it's image parsing that's throwing it, you can skip that for the time-being with `images:false`.
does the script keep going?
cheers

**Comment by j-rausch** [comment] 2018-09-06 03:39
Hey,
running
 ```dumpster /home/jrausch/data/wiki/2018_Aug_02/enwiki-latest-pages-articles.xml --html=true --images=false```
 indeed seems to skip that issue.
Now, I'm running into this one, though:
```
====error!===
{ MongoError: BSONObj size: 17043108 (0x1040EA4) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:580:63
    at authenticateStragglers (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:503:16)
    at Connection.messageHandler (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:539:5)
    at emitMessageHandler (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
  name: 'MongoError',
  message: 'BSONObj size: 17043108 (0x1040EA4) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  ok: 0,
  errmsg: 'BSONObj size: 17043108 (0x1040EA4) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  [Symbol(mongoErrorContextSymbol)]: {} }
(node:70336) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toJSON' of undefined
    at obj.col.insertMany.catch (/home/jrausch/.npm/lib/node_modules/dumpster-dive/src/worker/03-write-db.js:32:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:70336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:70336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by spencermountain** [comment] 2018-09-06 13:12
whoa!
16mb? something is up!
yeah that toJSON error looks like it's just bad reporting on my end.
here, on master i've added the `verbose` flag to the command, can you add `--verbose=true` and see if you can find the culprit for this one too?

**Comment by j-rausch** [comment] 2018-09-06 18:19
Sure, I ran `dumpster` (current `master`) again:
It doesn't look like `verbose=true` changes much here, but this is the error message in any case:
```
====error!===
{ MongoError: BSONObj size: 16989061 (0x1033B85) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:580:63
    at authenticateStragglers (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:503:16)
    at Connection.messageHandler (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/pool.js:539:5)
    at emitMessageHandler (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
  name: 'MongoError',
  message: 'BSONObj size: 16989061 (0x1033B85) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  ok: 0,
  errmsg: 'BSONObj size: 16989061 (0x1033B85) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  [Symbol(mongoErrorContextSymbol)]: {} }
(node:12180) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toJSON' of undefined
    at obj.col.insertMany.catch (/home/jrausch/.npm/lib/node_modules/dumpster-dive/src/worker/03-write-db.js:32:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:12180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Without the `images=false` option, the errors are printed with the current article title, e.g.:
```
---Error on "List of submarine sandwich restaurants"
TypeError: i.json is not a function
    at data.images.doc.images.map.i (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/toJson.js:43:43)
    at Array.map (<anonymous>)
    at toJSON (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/toJson.js:43:32)
    at Document.json (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/wtf_wikipedia/src/document/Document.js:152:12)
    at parseWiki (/home/jrausch/.npm/lib/node_modules/dumpster-dive/src/worker/02-parseWiki.js:31:18)
    at SundayDriver.each (/home/jrausch/.npm/lib/node_modules/dumpster-dive/src/worker/index.js:29:16)
    at SundayDriver.doChunk (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/index.js:38:8)
    at doit (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/index.js:77:10)
    at SundayDriver.onData (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/index.js:87:3)
    at ReadStream.stream.on (/home/jrausch/.npm/lib/node_modules/dumpster-dive/node_modules/sunday-driver/src/02-start.js:15:10)
```

**Comment by spencermountain** [comment] 2018-09-06 20:01
thanks, i'll take a look.
cheers

**Comment by j-rausch** [comment] 2018-09-10 22:58
Hi Spencer,
Did you find out what's going on in these cases? 
I was hoping to use the next stable version of `dumpster-dive` with updated `wtf_wikipedia`, where #58 is resolved, before doing more downstream-processing.
Let me know if I can help. 
Thanks!

**Comment by spencermountain** [comment] 2018-09-11 17:53
hey Johannes. yeah, i reproduced this sandwhich error, and  [made an issue](https://github.com/spencermountain/wtf_wikipedia/issues/172) for the next wtf release.

i'm a bit worried about that 16mb page error. I haven't reproduced it, but will try hopefully later today.
if you wanna get closer, i think the verbose flag just isn't passing-through from the CLI. you should be able to see each page title as it's processing with this:
```js
let options = {
  file: path,
  db: dbName,
 verbose: true
}
dumpster(options)
```
that should help us find what is the heck is up.

**Comment by j-rausch** [comment] 2018-09-12 00:37
Hi Spencer, thanks for the hint and update! Using this config, I get following logs for one single worker:
```
...
   #0  - Espionage
   #0  - Exile (1995 video game series)
   #0  - Reizei
   #0  - Emperor Kazan
   #0  - Ichijō
   #0  - Sanjō
   #0  - Elvis Costello
   #0  - Epilepsy
   #0  - Extrasensory perception

     current: 1,486 pages - "Domitian"     

====error!===
{ MongoError: BSONObj size: 16960558 (0x102CC2E) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"
    at /home/jrausch/git/dumpster-dive/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:580:63
    at authenticateStragglers (/home/jrausch/git/dumpster-dive/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:503:16)
    at Connection.messageHandler (/home/jrausch/git/dumpster-dive/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:539:5)
    at emitMessageHandler (/home/jrausch/git/dumpster-dive/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/home/jrausch/git/dumpster-dive/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
  name: 'MongoError',
  message: 'BSONObj size: 16960558 (0x102CC2E) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  ok: 0,
  errmsg: 'BSONObj size: 16960558 (0x102CC2E) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "pages"',
  code: 10334,
  codeName: 'BSONObjectTooLarge',
  [Symbol(mongoErrorContextSymbol)]: {} }
(node:14517) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toJSON' of undefined
    at obj.col.insertMany.catch (/home/jrausch/git/dumpster-dive/src/worker/03-write-db.js:32:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:14517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

     current: 1,950 pages - "Extrasensory perception"     


     current: 1,950 pages - "Extrasensory perception"     


     current: 1,950 pages - "Extrasensory perception"     
...
```
So it seems that the individual workers terminate after encountering the 16mb page error.

**Comment by j-rausch** [comment] 2018-09-12 03:11
Small update:
A workaround for this seems to be looping over all pages and `insertOne` them one-by-one. It's probably still worth investigating what causes these big objects.

**Comment by spencermountain** [comment] 2018-09-12 16:14
oh hey @j-rausch I bet I know what's happening, it's that the batch writing of pages is >16mb, not any single page.
will you try lowering the `batch_size`?
```
let options = {
  file: path,
  db: dbName,
  verbose: true,
  batch_size:100
}
dumpster(options)
```
got a fix the the other one, behind a couple others before a release
thanks

**Comment by spencermountain** [comment] 2018-09-12 16:14
are you running on a single-core machine? That may contribute somehow.

**Comment by j-rausch** [comment] 2018-09-12 18:50
Hi Spencer,
Thanks, I tried some batch size variations, and for 100 the error didn't pop up anymore. 
Do you have an idea what might cause these big page sizes, considering that images might even be turned off?

**Comment by spencermountain** [comment] 2018-09-12 18:58
ah, that's great. the default is to write 10,000 at once.
i haven't experimented with which size is fastest.
can you try it at, say 8k? what's the highest you can get without the error?

**Comment by spencermountain** [comment] 2018-09-12 20:29
fixed the `i.json` sandwhich error on 3.6.0

**Comment by j-rausch** [comment] 2018-09-12 21:46
Awesome, thanks a lot!
I didn't check thoroughly with the newest version yet, because of some new error (#60), but yesterday `batch_size=100` was indeed the highest number that yielded no errors. (200 occasionally resulted in 16mb errors, if I remember correctly)

**Comment by aymansalama** [comment] 2018-09-18 07:48
Thank you guys for the wonderful chat. I went through your comments as i had the same problem. i have been trying for three days now and i thought it was my mistake. currently the cpus are still hot and working hard again. I used your recommendation above and it seems to be working. I have passed 40K pages which is a first since i tried. 

below is the command that I used based on your recommendations. I got GCP with 24 Core, and i set the workers to 20 cores. but it seems that it never cross 5 cores. I have no idea why. it seems that it starts hot with 20 cores and then suddenly after a second it goes down to 5 cores. I can see that behaviour from "top" command. 

Super thanks guys. 

sudo nohup dumpster enwiki-latest-pages-articles.xml --html=true --images=false --batch_size 100 --verbose true --workers 20&

**Comment by aymansalama** [comment] 2018-09-18 13:41
Finally got it, 
enwiki  10.876GB
      👍  closing down.
     -- final count is 1,274,403 pages --
       took 6.0 hours
              🎉

**Comment by spencermountain** [comment] 2018-09-18 18:31
anyone have any opinions on [this](https://www.npmjs.com/package/physical-cpu-count)?

**Comment by aymansalama** [comment] 2018-09-21 02:51
@spencermountain i have manage to upload all wiki languages. I placed all bz2 files in one folder. and then loop with dumpster. the script hanged many times with no output. and for the sake of simplicity, I ignored the language that failed. the xml lang that failed for some reasons are:
howiki
krwiki
kswiki
kuwiki
kvwiki
kwwiki
ngwiki
towiki

the log file for all language with verbose option is 948M. but as far as i have seen, when the script is not utilising any cpu, the output is just blank or stuck at some page. There is a possibility that I have done something wrong as the script took 2 days to finish including the time that the script hang, and i was sleep. usually, i will kill the process and rerun my script again. strangely, sometimes when i kill the process of dumpster or node, the process in the background will start again automatically. 

**here is the script **
for i in `ls *.bz2`
do
        date
        echo $i
        echo '#######################Start'
        bunzip2 /data/wiki_data/all_lang_wiki/bunzip2/$i
        dumpster /data/wiki_data/all_lang_wiki/bunzip2/`echo $i | cut -d'.' -f1,2` --html=true --images=false --batch_size 100 --verbose true --workers 20
        echo
        echo

done

** Here is the db sizes after upload ** 


aawiki | , | 32,768
abwiki | , | 712,704
afwiki | , | 17,170,432
akwiki | , | 110,592
amwiki | , | 765,952
anwiki | , | 29,958,144
arwiki | , | 171,327,488
aswiki | , | 3,616,768
avwiki | , | 2,170,880
aywiki | , | 2,039,808
azwiki | , | 32,808,960
bawiki | , | 10,997,760
bewiki | , | 64,552,960
bgwiki | , | 184,958,976
bhwiki | , | 1,822,720
biwiki | , | 102,400
bmwiki | , | 65,536
bnwiki | , | 312,180,736
bowiki | , | 1,318,912
brwiki | , | 9,711,616
bswiki | , | 34,865,152
cawiki | , | 787,673,088
cewiki | , | 31,363,072
chwiki | , | 335,872
cowiki | , | 475,136
crwiki | , | 61,440
cuwiki | , | 339,968
cvwiki | , | 21,164,032
cywiki | , | 165,445,632
dawiki | , | 245,534,720
dewiki | , | 1,131,925,504
dvwiki | , | 1,814,528
dzwiki | , | 94,208
eewiki | , | 73,728
elwiki | , | 69,996,544
enwiki | , | 11,677,663,232
eowiki | , | 175,362,048
eswiki | , | 684,331,008
etwiki | , | 77,262,848
euwiki | , | 58,560,512
fawiki | , | 283,185,152
ffwiki | , | 167,936
fiwiki | , | 973,836,288
fjwiki | , | 81,920
fowiki | , | 3,166,208
frwiki | , | 984,412,160
fywiki | , | 9,879,552
gawiki | , | 8,970,240
gdwiki | , | 8,232,960
glwiki | , | 89,206,784
gnwiki | , | 5,279,744
guwiki | , | 16,715,776
gvwiki | , | 696,320
hawiki | , | 2,101,248
hewiki | , | 438,804,480
hiwiki | , | 26,284,032
hrwiki | , | 239,976,448
htwiki | , | 2,392,064
huwiki | , | 367,312,896
hywiki | , | 210,993,152
hzwiki | , | 32,768
iawiki | , | 1,892,352
idwiki | , | 641,597,440
iewiki | , | 839,680
igwiki | , | 253,952
iiwiki | , | 49,152
ikwiki | , | 98,304
iowiki | , | 10,612,736
iswiki | , | 17,416,192
itwiki | , | 601,653,248
iuwiki | , | 102,400
jawiki | , | 1,830,240,256
jvwiki | , | 7,860,224
kawiki | , | 35,467,264
kgwiki | , | 77,824
kiwiki | , | 106,496
kjwiki | , | 49,152
kkwiki | , | 98,799,616
klwiki | , | 442,368
kmwiki | , | 2,940,928
knwiki | , | 22,204,416
kowiki | , | 204,967,936
kywiki | , | 8,876,032
lawiki | , | 68,612,096
lbwiki | , | 35,602,432
lgwiki | , | 385,024
liwiki | , | 3,698,688
lnwiki | , | 471,040
lowiki | , | 1,961,984
ltwiki | , | 308,752,384
lvwiki | , | 99,717,120
mgwiki | , | 6,590,464
mhwiki | , | 32,768
miwiki | , | 475,136
mkwiki | , | 59,199,488
mlwiki | , | 87,662,592
mnwiki | , | 4,562,944
mrwiki | , | 47,075,328
mswiki | , | 84,762,624
mtwiki | , | 7,180,288
mywiki | , | 9,654,272
nawiki | , | 208,896
newiki | , | 3,284,992
nlwiki | , | 1,221,115,904
nnwiki | , | 30,019,584
nowiki | , | 553,197,568
nvwiki | , | 929,792
nywiki | , | 327,680
ocwiki | , | 66,531,328
omwiki | , | 712,704
orwiki | , | 13,430,784
oswiki | , | 946,176
pawiki | , | 13,148,160
piwiki | , | 49,152
plwiki | , | 429,785,088
pswiki | , | 3,653,632
ptwiki | , | 355,381,248
quwiki | , | 10,919,936
rmwiki | , | 1,404,928
rnwiki | , | 69,632
rowiki | , | 125,026,304
ruwiki | , | 3,401,510,912
rwwiki | , | 81,920
sawiki | , | 12,910,592
scwiki | , | 393,216
sdwiki | , | 10,653,696
sewiki | , | 696,320
sgwiki | , | 184,320
siwiki | , | 3,522,560
skwiki | , | 69,214,208
slwiki | , | 51,200,000
smwiki | , | 196,608
snwiki | , | 102,400
sowiki | , | 1,101,824
sqwiki | , | 17,866,752
srwiki | , | 683,880,448
sswiki | , | 49,152
stwiki | , | 114,688
suwiki | , | 6,234,112
svwiki | , | 1,006,587,904
swwiki | , | 18,956,288
tawiki | , | 62,373,888
tewiki | , | 30,339,072
tgwiki | , | 36,372,480
thwiki | , | 193,363,968
tiwiki | , | 77,824
tkwiki | , | 2,150,400
tlwiki | , | 39,768,064
tnwiki | , | 339,968
trwiki | , | 759,373,824
tswiki | , | 143,360
ttwiki | , | 15,925,248
twwiki | , | 114,688
tywiki | , | 94,208
ugwiki | , | 2,297,856
ukwiki | , | 307,081,216
urwiki | , | 29,523,968
uzwiki | , | 45,228,032
vewiki | , | 143,360
viwiki | , | 200,392,704
vowiki | , | 11,395,072
wawiki | , | 14,708,736
wowiki | , | 364,544
xhwiki | , | 139,264
yiwiki | , | 6,639,616
yowiki | , | 2,736,128
zawiki | , | 569,344
zhwiki | , | 836,706,304
zuwiki | , | 266,240

**Comment by spencermountain** [comment] 2018-09-21 16:59
wow!
@aymansalama that's awesome. I think you get the award for most-ambitious application.
I'll take a look at the failing wikis.
I am gonna try to release v6 of the parser today. This will change the json output a bit from the current version. I'll also try to get something more valuable in the logging, that could diagnose the hanging issues you're seeing.
what article-count did you get for enwiki, etc? is it in the 4-5million range?
cheers

**Comment by spencermountain** [comment] 2018-10-29 20:56
closing this, 200 max seems to work, and there's a notice on the readme about the possible error.

**Closed by spencermountain** 2018-10-29 20:56 UTC
Labels: bug, next-release
